[package]
name = "rust-http"
version = "0.1.0"
authors = ["pariosa"]

[dependencies]
futures = "0.1.14"
futures-cpupool = "0.1.5"
hyper = "0.11"
clap = "2.25.0"
threadpool = "1.4.0"
net2 = "0.2"
libc = "0.2.4"
error-type = "0.1.2"